<?
$canonicalArr = ["/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_stil_80_01_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_stil_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_latsio_dlya_doma.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_latsio_dlya_doma_.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_latsio.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_latsio_dlya_doma_.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_stil_80_02_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_stil_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_monarkh_dlya_doma.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_monarkh_dlya_doma_.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_monarkh.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_monarkh_dlya_doma_.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_denver_80_05_03_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_denver_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_denver_80_06_03_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_denver_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_milano_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_milano_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_milano_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_milano_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_london_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_london_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_london_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_london_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_luna_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_luna_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_luna_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_luna_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_rafael_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_rafael_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_rafael_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_rafael_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_leo_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_leo_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_leo_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_leo_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_barselona_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_barselona_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_barselona_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_barselona_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_dublin_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_dublin_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_dublin_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_dublin_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_vikont_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_vikont_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_vikont_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_vikont_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_tokio_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_tokio_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_marsel_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_marsel_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_marsel_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_marsel_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_provans_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_provans_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_provans_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_provans_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_aero_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_aero_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_aero_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_aero_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_tokio_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_tokio_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_tokio_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_tokio_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_millenium_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_millenium_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_millenium_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_millenium_dlya_kvartiry_.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_tsezar_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_tsezar_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_tsezar_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_tsezar_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_triumf_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_triumph_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_liniya_svetlaya_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_liniya_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_liniya_temnaya_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_liniya_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_neon_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_neon_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_neon_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_neon_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_sparta_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_sparta_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_sparta_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_sparta_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_bogema_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_bogema_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_bogema_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_bogema_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_versache_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_versache_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_versache_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_versache_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_oktavio_dlya_doma_i_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_oktavio_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_oktavio_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_oktavio_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_britaniya_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_britaniya_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_grand_svetlyy_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_grand_dlya_kvartiry.html",
"/catalog-dverei/stalnaya-liniya/metallicheskaya_dver_grand_temnyy_dlya_kvartiry.html"=>"/catalog-dverei/stalnaya-liniya/vkhodnaya_dver_grand_dlya_kvartiry.html"];
$url = preg_replace("#\?.*?$#", "", $_SERVER["REQUEST_URI"]);
if($canonicalArr[$url]) {
	$canon = $canonicalArr[$url];
} elseif(!empty($_GET)) {
	$canon = preg_replace("#[&|?].*$#", "", $_SERVER["REQUEST_URI"]);
} else {
	$canon = false;
}
